apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  databaseUrl: "postgresql+asyncpg://neondb_owner:npg_D6pTXEoSBn5V@ep-red-mouse-adokxnx6-pooler.c-2.us-east-1.aws.neon.tech/neondb"
  secretKey: "NDUKy9s9fo2pDo4EytYIdpleBpWCWCdU"
  algorithm: "HS256"
  accessTokenExpireMinutes: "30"
  backendCorsOrigins: '["http://localhost:3000", "http://127.0.0.1:3000", "http://127.0.0.1:8000/", "http://localhost:30000", "http://localhost:30001"]'
  geminiApiKey: "AIzaSyDeJEghngK9E9LAsLjsg0R4448qL_4NDR8"